group=io.github.anxelok.loom
mcVersion=26.1.1
# This is the current API version for plugin metadata files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion=26.1.1
channel=STABLE
paperRef=77c0866f5f60a74f475e94612a391b22df5cefe3

# Set to true while updating Minecraft version
updatingMinecraft=false

org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.workers.max=12
org.gradle.vfs.watch=false
